version: "3.1"

services:
  idnarea:
    build: "./"
    image: idnarea:latest
    container_name: idnarea
    hostname: idnarea
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    restart: always
    env_file:
      - ./.env